### ISSUE TITLE
Cell formats with square brackets can lead to errors or warnings while opening workbook

### ISSUE THREAD

**Issue by jazzthief81** [cubing/wca-workbook-assistant#25]
Examples of workbooks with errors:

Registration list.xlsx
[$-14409]yyyy-mm-dd;@

KansasCubeOff2012.xlsx
[$-409]0.00

Workbooks with errors don't open up at all and the following exception is runtime thrown:

java.lang.NullPointerException
    at org.apache.poi.ss.format.CellFormat.getApplicableFormatPart(CellFormat.java:372)
    at org.apache.poi.ss.format.CellFormat.apply(CellFormat.java:264)
    at org.worldcubeassociation.ui.WorkbookTableDataExtractor.extractTableData(WorkbookTableDataExtractor.java:48)
    at org.worldcubeassociation.ui.WorkbookTableDataExtractor.extractTableData(WorkbookTableDataExtractor.java:25)
    at org.worldcubeassociation.workbook.WorkbookTableDataExtractorTest.handleFile(WorkbookTableDataExtractorTest.java:28)
    at org.worldcubeassociation.workbook.AbstractWorkbookTest.handleFile(AbstractWorkbookTest.java:38)
    at org.worldcubeassociation.workbook.AbstractWorkbookTest.start(AbstractWorkbookTest.java:22)
    at org.worldcubeassociation.workbook.WorkbookTableDataExtractorTest.main(WorkbookTableDataExtractorTest.java:15)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

Examples of workbooks with warnings:

amstelveenopen2012.xlsx
WARNING: Invalid format: "[$-413]d/mmm/yyyy;"

KarstulaOpen2012_results.xls
WARNING: Invalid format: "[$-409]0.00"

RCMO-2011 RESULTS.xls
WARNING: Invalid format: "[$-409]d-mmm-yy;"

Registro Competidores.xls
WARNING: Invalid format: "[$-14409]yyyy-mm-dd;"

Workbooks with warnings still open and the warning is logged to the console.

**Comment by ZZareyan** [comment]
Hi jazzthief81,

Very nice and helpful article, but it's not satisfied my case, which cellFormatString = _([$$-409]* #,##0.00_);_([$$-409]* \(#,##0.00\);_([$$-409]* "-"??_);_(@_)
I need to do additional string parsing.

Thanks.

**Comment by jfly** [comment]
@ZZareyan, could you upload a broken workbook (please strip any private information first)? If that's proves to be annoying or too much work, you can email software-admins@worldcubeassociation.org.
